### ISSUE TITLE
swiftuiで聞きたいこと

### ISSUE THREAD

**Issue by kojake** [kojake/Lost_item_sharing_app#1]
高津さん

swiftuiで質問があります。
初めてアプリを開いた時にしか表示されないviewを表示するコードを書きたいのですが
chatgptはuserdefaultsを使えと言っていたのですがそれ以外にxcodeが用意しているコードはないでしょうか？

海斗

**Comment by yuuki00682200** [comment]
これ今見ました！すみません、気づいて欲しい時は　@kojake のようにメンションしてくれると気が付きやすいです。

初めてアプリを開いたときに表示する画面としては、launch SCREENというものが一般的ですね。

https://qiita.com/Hackenbacker/items/85c8f785c2df6f1f7534

**Comment by kojake** [comment]
ありがとうございます！
